name: Branch Creation

on:
  workflow_dispatch:
    inputs:
      branch_name:
        required: true
        description: "Specify your branch name, make it short"

jobs:
  create-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
    
    - name: Create global configs
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
    
    - name: Create and switch to a new branch
      run: |
        branchName="${GITHUB_ACTOR}-${{ github.event.inputs.branch_name }}"
        git checkout --orphan $branchName
        git rm -rf .
        echo "branchName=$branchName" >> $GITHUB_ENV

    - name: Backup .github folder
      run: |
        mkdir -p tmp_github
        cp -R .github/* tmp_github/ || true

    - name: Clone the remote repository
      run: |
        git clone https://github.com/Anuken/Mindustry.git tmpFolder
        cp -R tmpFolder/* .
        rm -rf tmpFolder
    
    - name: Restore the .github folder with workflows
      run: |
        mkdir -p .github
        cp -R tmp_github/* .github/ || true
        rm -rf tmp_github

    - name: Push to the new branch
      run: |
        git add .
        git commit -m "Initialize branch"
        git push origin $branchName
